# Maxpooling

In [1]:
import numpy as np

In [10]:
def max_pooling_forward_naive(x, pool_param):
    N, C, H, W = x.shape
    HH, WW, stride = pool_param["pool_height"], pool_param["pool_width"], pool_param["stride"]
    H_out = 1 + int((H - HH) / stride)
    W_out = 1 + int((W - WW) / stride)
    out = np.zeros((N, C, H_out, W_out))
    
    for i in range(H_out):
        for j in range(W_out):
            out[..., i, j] = np.max(x[..., i * stride: i * stride + HH, j * stride: j * stride + WW], axis=(2,3))
    
    cache = (x, out, pool_param)
    return out, cache

In [38]:
def max_pooling_backward_naive(dout, cache):
    x, out, pool_param = cache
    N, C, H_out, W_out = dout.shape
    HH, WW, stride = pool_param["pool_height"], pool_param["pool_width"], pool_param["stride"]
    dx = np.zeros_like(x)
    
    for i in range(H_out):
        for j in range(W_out):
            # 计算位置
            mark = x[..., i * stride: i * stride + HH, j * stride: j * stride + WW] == out[..., i, j]
            dx[..., i * stride: i * stride + HH, j * stride: j * stride + WW] = mark * dout[..., i, j]
    
    return dx

In [12]:
x = np.arange(16).reshape(1, 1, 4, 4)
pool_param = {"pool_height": 2, "pool_width": 2, "stride": 2}

In [31]:
out, cache = max_pooling_forward_naive(x, pool_param)
print("x: \n", x)
print("out: \n", out)

x: 
 [[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]]]
out: 
 [[[[ 5.  7.]
   [13. 15.]]]]


In [41]:
dout = np.arange(4, 0, -1).reshape(1, 1, 2, 2)
dx = max_pooling_backward_naive(dout, cache)
print("dx: \n", dx)

dx: 
 [[[[0 0 0 0]
   [0 4 0 3]
   [0 0 0 0]
   [0 2 0 1]]]]


# BN

In [ ]:
def spatial_batchnorm_forward(x, gamma, beta, bn_param):
    pass

In [ ]:
def spatial_batchnorm_backward(dout, cache):
    pass